AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    b306eb8c-5ecb-4412-b798-aacd8ea59538:
      size:
        width: 940
        height: 610
      position:
        x: 520
        'y': 120
      z: 0
      embeds:
        - b2a98d35-4cbc-4108-bff8-f19ae675338c
        - 25e671b5-7908-46e8-83de-75256ea383b0
        - 94239519-789d-40dd-b6bd-23a1952199ab
        - f979e2ce-b931-41fb-9304-8df300731a9c
        - f3ead92a-a5ff-47b6-acb6-d1c3d357f79f
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
    4f75ac32-3e10-41ee-ab17-77ced5616e42:
      size:
        width: 270
        height: 410
      position:
        x: 690
        'y': 220
      z: 1
      parent: b306eb8c-5ecb-4412-b798-aacd8ea59538
      embeds:
        - ac8936fb-f3ec-4a94-9618-31a5f77ab90e
        - 1e7ccba4-ca02-47b9-b631-506d11f3731f
        - 2e30a8f4-adc7-4dc0-beac-be8bdacf9364
    f3ead92a-a5ff-47b6-acb6-d1c3d357f79f:
      size:
        width: 260
        height: 410
      position:
        x: 1000
        'y': 220
      z: 1
      parent: b306eb8c-5ecb-4412-b798-aacd8ea59538
      embeds:
        - bdbb8aa4-fcfd-46d7-a29a-72ed6c1e4b2e
    2e30a8f4-adc7-4dc0-beac-be8bdacf9364:
      size:
        width: 60
        height: 60
      position:
        x: 860
        'y': 290
      z: 2
      parent: 4f75ac32-3e10-41ee-ab17-77ced5616e42
      embeds: []
      iscontainedinside:
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
      dependson:
        - bdbb8aa4-fcfd-46d7-a29a-72ed6c1e4b2e
    6f190cf5-0e4a-4476-8668-4521290cfbfa:
      size:
        width: 60
        height: 60
      position:
        x: 270
        'y': 370
      z: 0
      embeds: []
      dependson:
        - e9c70023-3c71-4159-862b-739b3d39fc03
    1e7ccba4-ca02-47b9-b631-506d11f3731f:
      size:
        width: 60
        height: 60
      position:
        x: 860
        'y': 450
      z: 2
      parent: 4f75ac32-3e10-41ee-ab17-77ced5616e42
      embeds: []
      iscontainedinside:
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
      dependson:
        - bdbb8aa4-fcfd-46d7-a29a-72ed6c1e4b2e
    e9c70023-3c71-4159-862b-739b3d39fc03:
      size:
        width: 60
        height: 60
      position:
        x: 490
        'y': 370
      z: 0
      embeds: []
      dependson:
        - ac8936fb-f3ec-4a94-9618-31a5f77ab90e
    bdbb8aa4-fcfd-46d7-a29a-72ed6c1e4b2e:
      size:
        width: 60
        height: 60
      position:
        x: 1100
        'y': 370
      z: 2
      parent: f3ead92a-a5ff-47b6-acb6-d1c3d357f79f
      embeds: []
    f979e2ce-b931-41fb-9304-8df300731a9c:
      size:
        width: 60
        height: 60
      position:
        x: 1330
        'y': 230
      z: 1
      parent: b306eb8c-5ecb-4412-b798-aacd8ea59538
      embeds: []
      dependson:
        - b306eb8c-5ecb-4412-b798-aacd8ea59538
    0c52bcdc-aeec-4b28-a844-04edce432dde:
      size:
        width: 60
        height: 60
      position:
        x: 490
        'y': 290
      z: 0
      embeds: []
      dependson:
        - e9c70023-3c71-4159-862b-739b3d39fc03
    94239519-789d-40dd-b6bd-23a1952199ab:
      size:
        width: 60
        height: 60
      position:
        x: 1330
        'y': 320
      z: 1
      parent: b306eb8c-5ecb-4412-b798-aacd8ea59538
      embeds: []
      dependson:
        - b306eb8c-5ecb-4412-b798-aacd8ea59538
    25e671b5-7908-46e8-83de-75256ea383b0:
      size:
        width: 60
        height: 60
      position:
        x: 1330
        'y': 410
      z: 1
      parent: b306eb8c-5ecb-4412-b798-aacd8ea59538
      embeds: []
      dependson:
        - b306eb8c-5ecb-4412-b798-aacd8ea59538
    b2a98d35-4cbc-4108-bff8-f19ae675338c:
      size:
        width: 60
        height: 60
      position:
        x: 1330
        'y': 500
      z: 1
      parent: b306eb8c-5ecb-4412-b798-aacd8ea59538
      embeds: []
      dependson:
        - b306eb8c-5ecb-4412-b798-aacd8ea59538
    ac8936fb-f3ec-4a94-9618-31a5f77ab90e:
      size:
        width: 60
        height: 60
      position:
        x: 720
        'y': 370
      z: 2
      parent: 4f75ac32-3e10-41ee-ab17-77ced5616e42
      embeds: []
      isassociatedwith:
        - 2e30a8f4-adc7-4dc0-beac-be8bdacf9364
        - 1e7ccba4-ca02-47b9-b631-506d11f3731f
      iscontainedinside:
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
        - 4f75ac32-3e10-41ee-ab17-77ced5616e42
    a68fa4dd-f513-412e-8ea9-50daa4820743:
      size:
        width: 60
        height: 60
      position:
        x: 490
        'y': 220
      z: 0
      embeds: []
      dependson:
        - e9c70023-3c71-4159-862b-739b3d39fc03
    007de3c1-7da1-49d7-b6b6-55b5d3db5ec7:
      source:
        id: 6f190cf5-0e4a-4476-8668-4521290cfbfa
      target:
        id: e9c70023-3c71-4159-862b-739b3d39fc03
      z: 4
    1407c5e1-8583-4d59-a1a7-fdd077887582:
      source:
        id: a68fa4dd-f513-412e-8ea9-50daa4820743
      target:
        id: e9c70023-3c71-4159-862b-739b3d39fc03
      z: 5
    11649cee-bb97-4546-9d13-a5316e592bc8:
      source:
        id: 0c52bcdc-aeec-4b28-a844-04edce432dde
      target:
        id: e9c70023-3c71-4159-862b-739b3d39fc03
      z: 6
    c8eec735-69b1-420a-99ef-9ee8a03358a3:
      source:
        id: e9c70023-3c71-4159-862b-739b3d39fc03
      target:
        id: ac8936fb-f3ec-4a94-9618-31a5f77ab90e
      z: 7
    0697002b-719a-4851-8331-4eea585ae5e9:
      source:
        id: ac8936fb-f3ec-4a94-9618-31a5f77ab90e
      target:
        id: 2e30a8f4-adc7-4dc0-beac-be8bdacf9364
      z: 8
    401b4d93-96e1-4605-b410-fc837265dd85:
      source:
        id: ac8936fb-f3ec-4a94-9618-31a5f77ab90e
      target:
        id: 1e7ccba4-ca02-47b9-b631-506d11f3731f
      z: 9
    3d842e4d-3966-4d2e-aa87-84762f27d666:
      source:
        id: ac8936fb-f3ec-4a94-9618-31a5f77ab90e
        selector: 'g:nth-child(1) g:nth-child(4) g:nth-child(4) circle:nth-child(1)     '
        port: 'AWS::ContainedInsideLink-AWS::EC2::Subnet-Subnets'
      target:
        id: 4f75ac32-3e10-41ee-ab17-77ced5616e42
      z: 11
    e7ca5800-c999-46ef-82da-5a4960cf0012:
      source:
        id: 6f190cf5-0e4a-4476-8668-4521290cfbfa
      target:
        id: b306eb8c-5ecb-4412-b798-aacd8ea59538
      z: 10
    5157f4bf-0d66-4af6-8673-76f4328856e3:
      source:
        id: 4f75ac32-3e10-41ee-ab17-77ced5616e42
        selector: 'g:nth-child(1) g:nth-child(5) g:nth-child(3) circle:nth-child(1)     '
        port: 'AWS::ContainedInsideLink-AWS::EC2::VPC-VpcId'
      target:
        id: b306eb8c-5ecb-4412-b798-aacd8ea59538
      z: 12
    7627b2b7-4f39-48d9-b5c5-ac67bec32e80:
      source:
        id: 2e30a8f4-adc7-4dc0-beac-be8bdacf9364
      target:
        id: bdbb8aa4-fcfd-46d7-a29a-72ed6c1e4b2e
      z: 11
    bd17cbf8-eed6-45ab-8188-68042e3db467:
      source:
        id: 1e7ccba4-ca02-47b9-b631-506d11f3731f
      target:
        id: bdbb8aa4-fcfd-46d7-a29a-72ed6c1e4b2e
      z: 12
    816c881f-439b-4323-849d-1902761384bb:
      source:
        id: f979e2ce-b931-41fb-9304-8df300731a9c
      target:
        id: b306eb8c-5ecb-4412-b798-aacd8ea59538
      z: 13
    b282ed6d-f570-4451-8bd3-f9732eddbf55:
      source:
        id: 94239519-789d-40dd-b6bd-23a1952199ab
      target:
        id: b306eb8c-5ecb-4412-b798-aacd8ea59538
      z: 14
    d5173c96-8e6c-4cd7-9fb7-21f9dc449030:
      source:
        id: 25e671b5-7908-46e8-83de-75256ea383b0
      target:
        id: b306eb8c-5ecb-4412-b798-aacd8ea59538
      z: 15
    753769b0-4d3f-47eb-b44e-c9242e88ff20:
      source:
        id: b2a98d35-4cbc-4108-bff8-f19ae675338c
      target:
        id: b306eb8c-5ecb-4412-b798-aacd8ea59538
      z: 16
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b306eb8c-5ecb-4412-b798-aacd8ea59538
  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 4f75ac32-3e10-41ee-ab17-77ced5616e42
  PrivateSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
    Metadata:
      'AWS::CloudFormation::Designer':
        id: f3ead92a-a5ff-47b6-acb6-d1c3d357f79f
  WebServer:
    Type: 'AWS::EC2::Instance'
    Properties:
      NetworkInterfaces:
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 2e30a8f4-adc7-4dc0-beac-be8bdacf9364
    DependsOn:
      - MySQL
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 6f190cf5-0e4a-4476-8668-4521290cfbfa
    DependsOn:
      - Route53
  WebApp:
    Type: 'AWS::EC2::Instance'
    Properties:
      NetworkInterfaces:
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
        - SubnetId: !Ref PublicSubnet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1e7ccba4-ca02-47b9-b631-506d11f3731f
    DependsOn:
      - MySQL
  Route53:
    Type: 'AWS::EC2::Route'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e9c70023-3c71-4159-862b-739b3d39fc03
    DependsOn:
      - ElasticLoadBalancing
  MySQL:
    Type: 'AWS::RDS::OptionGroup'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: bdbb8aa4-fcfd-46d7-a29a-72ed6c1e4b2e
  IAM:
    Type: 'AWS::IAM::AccessKey'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: f979e2ce-b931-41fb-9304-8df300731a9c
    DependsOn:
      - VPC
  WAF:
    Type: 'AWS::WAF::ByteMatchSet'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0c52bcdc-aeec-4b28-a844-04edce432dde
    DependsOn:
      - Route53
  Backup:
    Type: 'AWS::Backup::BackupPlan'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 94239519-789d-40dd-b6bd-23a1952199ab
    DependsOn:
      - VPC
  CloudTrail:
    Type: 'AWS::CloudTrail::Trail'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 25e671b5-7908-46e8-83de-75256ea383b0
    DependsOn:
      - VPC
  CloudWatch:
    Type: 'AWS::CloudWatch::AnomalyDetector'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b2a98d35-4cbc-4108-bff8-f19ae675338c
    DependsOn:
      - VPC
  ElasticLoadBalancing:
    Type: 'AWS::ElasticLoadBalancing::LoadBalancer'
    Properties:
      Subnets:
        - !Ref PublicSubnet
        - !Ref PublicSubnet
        - !Ref PublicSubnet
        - !Ref PublicSubnet
      Instances:
        - !Ref WebServer
        - !Ref WebApp
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ac8936fb-f3ec-4a94-9618-31a5f77ab90e
  Firewall:
    Type: 'AWS::NetworkFirewall::Firewall'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: a68fa4dd-f513-412e-8ea9-50daa4820743
    DependsOn:
      - Route53
  EC2VPCG21ISZ:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e7ca5800-c999-46ef-82da-5a4960cf0012